### PR TITLE
Feature -  Combine single and multiple config handling

### PR DESCRIPTION
**Pull request by rasmussl**
## Idea:
The current configuration for multiple configs isn't very nice and clean. 
Furthermore, there is no need for separate extensions and tasks for updating strings from a single Loco project and multiple Loco projects.

## Solution:
Therefore I removed the "updateLocoMultiple" task and updated the "updateLoco" task so that it handles all of the Loco string updates, no matter if it's one or multiple configs.
And I changed how the config data is provided to the plugin.

New plugin data structure:
```groovy
Loco {
    config {
        apiKey = 'YOUR_API_KEY'
        lang = ['de', 'fr'] // add as many languages as you want, they need to exist on localise.biz
        resDir = "$projectDir/src/main/res"
        defLang = 'de' // one language that will result as the default language and be put in values/strings.xml
        saveDefLangDuplicate = false // default (false): defLang will only be saved in values folder. If set to true, the defLang will also be saved in the specific folder (such as values-en)
        placeholderPattern = null // optional; regex pattern with leading ~, default -> null
        fileName = "strings" // optional; customise file name
        hideComments = false // optional; hide comments & loco metadata 
        tags = 'Android,!iOS' // optional; filter assets by comma-separated tag names. Match any tag with `*` and negate tags by prefixing with `!`. Whitespaces need to be replaced with _ (e.g. "Some tag" becomes "Some_tag").	 
        fallbackLang = 'en' // optional;, fallback language when not present
        orderByAssetId = false // optional; order assets alphabetically by Asset ID
        status = "translated" // optional; filter assets by status. Negate values by prefixing with !. e.g. "translated", or "!fuzzy".
        resourceNamePrefix = null // optional: string prefix for all resource names (default: null, no prefix)
        ignoreMissingTranslationWarnings = false // optional: use at your own risk, removes linting issues of missing translations
        index = null // optional: pass in a lookup key such as "id" or "text"
    }
    config {}
    .
    .
    config {}
}
```

Since this change breaks how the plugin works I suggest bumping the minor, meaning that if this is merged and released, it should be as v0.3.0.

I have updated the `README.md` to show the migration from 0.2.xx to 0.3.xx.

### CODE REVIEW

**Comment by rasmussl** [comment]
Hi @yannickpulver :)

I can't add reviewers, so I just left this message instead.

I know that this PR is a big change but I hope that you will consider it and if you don't want to make this change. I at least hope that you will update the multiple configs to use the `config(Closure)` function, provided in this PR, instead of the old approach.

Looking forward to hearing back from you! :)

**Comment by yannickpulver** [comment]
Hi @rasmussl 

Thanks for the PR! At a glance, it looks well prepared 🙌
I was on holiday last week, so with a bit of delay — I'll try to have a look at it this week!

**Comment by rasmussl** [comment]
Hi @yannickpulver 👋

No rush!
Glad to hear that you liked it at first glance! Since it's a breaking change I know I had to present it in the best possible way 🎁 

Let me know if you have any ideas and/or questions for the change.

**Review by yannickpulver — APPROVED** [review]
Looks fine to me! Thanks for the great improvements. Especially adding multiple configs looks much cleaner now.

**Comment by yannickpulver** [comment]
@rasmussl 
The only thing I noticed is that in `build.gradle.kts`, the config has now be provided like following:

```groovy
Loco {
    config(closureOf<LocoConfig> {
        apiKey = "..."
    })
}
```

It would be great if we can find a way around, so that we can use it similarly to `build.gradle`.

**Comment by yannickpulver** [comment]
@rasmussl 
Update:
Seems the following does the job. According to the [docs](https://docs.gradle.org/current/userguide/kotlin_dsl.html#groovy_closures_from_kotlin), it's better to use Action<T> instead of Closure, then the parsing works correctly for both `build.gradle` and `build.gradle.kts`:

```groovy
    void config(Action<LocoConfig> action) {
        LocoConfig config = new LocoConfig()
        project.configure([config], action)
        configList.add(config)
    }
```

I'll add it in a commit and if all works, ship 0.3.0

**Comment by rasmussl** [comment]
> @rasmussl 
> Update:
> Seems the following does the job. According to the [docs](https://docs.gradle.org/current/userguide/kotlin_dsl.html#groovy_closures_from_kotlin), it's better to use Action<T> instead of Closure, then the parsing works correctly for both `build.gradle` and `build.gradle.kts`:
> 
> ```groovy
>     void config(Action<LocoConfig> action) {
>         LocoConfig config = new LocoConfig()
>         project.configure([config], action)
>         configList.add(config)
>     }
> ```
> 
> I'll add it in a commit and if all works, ship 0.3.0 
> 
> 
> 

Perfect!

Sorry for missing the Kotlin issue!
Hope this ticket and your change will work 🎉

**Pull request merged**
